### ISSUE TITLE
Authentication Issue When Going Through Quick Start Guide

### ISSUE THREAD

**Issue by gregdotca** [boschkundendienst/guacamole-docker-compose#118]
I'm going through the four Quick Start Guide steps, but I keep getting authentication errors. I've tried this on Debian 11, Debian 12, and Ubuntu 24.04, but the result is the same.

I haven't changed anything in the Docker Compose file.

Here is the Docker Compose log:

```
guacamole_compose           | 02:21:29.938 [http-nio-8080-exec-2] WARN  o.a.g.e.AuthenticationProviderFacade - The "postgresql" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: postgresql" within your guacamole.properties.
guacamole_compose           | 02:21:29.941 [http-nio-8080-exec-2] ERROR o.a.g.rest.RESTExceptionMapper - Unexpected internal error: 
guacamole_compose           | ### Error querying database.  Cause: org.postgresql.util.PSQLException: The server requested SCRAM-based authentication, but the password is an empty string.
guacamole_compose           | ### The error may exist in org/apache/guacamole/auth/jdbc/user/UserMapper.xml
guacamole_compose           | ### The error may involve org.apache.guacamole.auth.jdbc.user.UserMapper.selectOne
guacamole_compose           | ### The error occurred while executing a query
guacamole_compose           | ### Cause: org.postgresql.util.PSQLException: The server requested SCRAM-based authentication, but the password is an empty string.
```

Does anyone know how to resolve this?

**Comment by heroes1412** [comment]
+1 upvote

**Comment by penxxy** [comment]
I encountered the same issue.

**Comment by spotdemo4** [comment]
It looks like [the environment variables changed](https://github.com/mike-jumper/guacamole-client/blob/bfae010ad9d909370b55aecc352bb87371c5a063/guacamole-docker/entrypoint.d/010-migrate-legacy-variables.sh#L92-L105) from `POSTGRES_X` to `POSTGRESQL_X`. They've also [dropped support for legacy container links](https://issues.apache.org/jira/browse/GUACAMOLE-374). 

I was also having an issue running behind a reverse proxy, as their [brute force protection](https://guacamole.apache.org/doc/gug/auth-ban.html) was banning the local container IP rather than the remote client IP. If you're behind a reverse proxy, you'll need to make sure it is passing the client's IP address to guacamole and set REMOTE_IP_VALVE_ENABLED to true ([more info](https://guacamole.apache.org/doc/gug/guacamole-docker.html#running-guacamole-behind-a-proxy)). Or you can disable the IP ban entirely by setting BAN_ENABLED to false.

The working compose file looks like:
```yaml
services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
    networks:
      - guacamole
    restart: always

  guacdb:
    container_name: guacdb
    image: postgres:15.2-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacpass
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
    networks:
      - guacamole
    restart: always

  guacamole:
    container_name: guac-guacamole
    image: guacamole/guacamole
    depends_on:
      - guacd
      - guacdb
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacdb
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: guacpass
      RECORDING_SEARCH_PATH: /record
      # uncomment if you're behind a reverse proxy
      # REMOTE_IP_VALVE_ENABLED: true
      # uncomment to disable brute-force protection entirely
      # BAN_ENABLED: false
      # https://guacamole.apache.org/doc/gug/guacamole-docker.html#running-guacamole-behind-a-proxy
    volumes:
      - ./record:/record:rw
    networks:
      - guacamole
    ports:
      - 8080/tcp
    restart: always

networks:
  guacamole:
    name: guacamole
```
