### ISSUE TITLE
Enable TOTP Extension via Docker-Compose

### ISSUE THREAD

**Issue by RealGrimbi** [boschkundendienst/guacamole-docker-compose#16]
Is there a way to enable TOTP via Docker Compose?
If I define the environment variables (mentioned below), everything starts but it seems like the extension is not loaded.
LDAP at the same time is working fine.

I have added the following in the environment section:
```
      TOTP_ISSUER: Apache Guacamole
      TOTP_DIGITS: 6
      TOTP_PERIOD: 30
      TOTP_MODE: sha1
```

If I check the guacamole_compose container the extension is in `/opt/guacamole/totp` but not in `/root/.guacamole/extensions/`

**Comment by RealGrimbi** [comment]
Just analysed the start.sh and noticed you need to set:
 ```
      TOTP_ENABLED: 'true'
      TOTP_ISSUER: Apache Guacamole
      TOTP_DIGITS: 6
      TOTP_PERIOD: 30
      TOTP_MODE: sha1
```
Afterwards it worked! No other Settings requiered.
If someone is having issue with ldap users not able to set it up you need to grant "change password" rigths to them. This was at least like this in Guacamole v1.2 ...

**Comment by ForceConstant** [comment]
@RealGrimbi are you saying you just had to enable this environment variables and you had access to TOTP without having to add extension?

**Comment by RealGrimbi** [comment]
@ForceConstant yes i still have it running like that ;-)

**Comment by samuelkneppel** [comment]
Hi, @RealGrimbi ,

Is this still working for you? I have tried setting it up by setting the environmental variables you mentioned above in the `guacd` container. My `docker_compose.yml` file looks like this:
```
<..>
  guacd:
    container_name: guacd_compose
    environment:
      TOTP_ENABLED: 'true'
      TOTP_ISSUER: Apache Guacamole
      TOTP_DIGITS: 6
      TOTP_PERIOD: 30
      TOTP_MODE: sha1
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
<..>
```

Is this the right place to put these variables? Because, after redeploying the containers using `reset.sh`, `prepare,sh`, and `docker-compose up -d`, upon login with the `guacadmin` account as well as another account with all permissions including the `change password' permission, I do not see a prompt to set up TOTP.

Any help would be much appreciated!
