### ISSUE TITLE
External Database Server

### ISSUE THREAD

**Issue by SnowyJaguar1034** [boschkundendienst/guacamole-docker-compose#64]
Hi, Since my [last](#63) 'issue' I've been fairly busy so I've not had time to look into deploying your stack/compose but I've now got a bit more time. I've recently setup a postgres database container to act as a central database for all of my containers instead of each of them having their own.
I just have a few questions about deploying you stack/compose.
- Does the guacamole service create it's own database (`POSTGRES_DATABASE: guacamole`) or does the postgres service do that?
If it doesn't I'd have to prepare that ahead of time myself right? Could I put something in the compose to make it for me?
- If I comment-out the postgres service do I just complete the following variables with the following values?
```
environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole (or whatever name I gave the database I created)
      POSTGRES_HOSTNAME: <IP_OF_MY_CENTRAL_DB_SERVER> e.g. 192.168.86.23:5432
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      # POSTGRES_USER: guacamole  (or whatever name I gave the user of the database I created)
```
- As I'm not using nginx (I plan on using traefik at some point) and I'm not using the postgres service then I don't need to run `prepare.sh` right?

Sorry for creating issues for these questions, If you had the 'Disscussions' feature enabled then I would have asked there.
