### ISSUE TITLE
branding.jar

### ISSUE THREAD

**Issue by q16marvin** [boschkundendienst/guacamole-docker-compose#86]
Hi,

thx for your yml file :) it helps me a lot :) i have add ldap variables and also working well. but i dont get branding.jar do change logo, do you know where i need to se this file?

Thx!
Erik

**Comment by q16marvin** [comment]
environment variable GUACAMOLE_HOME and a volume was enough to work, here my full yml file:

```
version: '2.0'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # guacamole
  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /opt/guacamole
      MYSQL_HOSTNAME: xxx.xxx.xxx.xxx
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole1
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: blabla
      LDAP_HOSTNAME: xxx.xxx.xxx.xxx
      LDAP_USER_BASE_DN: DC=gut,DC=blabla
      LDAP_PORT: 389
      LDAP_ENCRYPTION_METHOD: none 
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      LDAP_SEARCH_BIND_DN: CN=guacamole,CN=Users,DC=gut,DC=blabla
      LDAP_SEARCH_BIND_PASSWORD: blabla
      REMOTE_IP_VALVE_ENABLED: true
      PROXY_IP_HEADER: x-forwarded-for
      PROXY_BY_HEADER: x-forwarded-by
      PROXY_PROTOCOL_HEADER: X-Forwarded-Proto
      
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork_compose:
    volumes:
    - ./extensions:/opt/guacamole/extensions
    ports:
    - 8086:8080/tcp
    restart: always
```
